### ISSUE TITLE
Unknown dashed properties containing "left" should not be flipped

### ISSUE THREAD

**Issue by Krinkle** [cssjanus/cssjanus#21]
Input:

``` css
.foo {
    x-left-y: 10px;
}
```

Output should be unchanged, but isn't:

``` css
.foo {
    x-right-y: 10px;
}
```
