### ISSUE TITLE
mirroring is not enough

### ISSUE THREAD

**Issue by NiviJah** [cssjanus/cssjanus#34]
Some rules need to be ADDED in addition to just flipping, in order to "zero out" the previous rule.

Example:
```css
.class {
position: absolute;
left:0;
}
.class2 {
margin-left:20px;
}
```
**Should be transformed to:**
```css
.class {
position: absolute;
right:0;
left:auto //addition
}
.class2 {
margin-right:20px;
margin-left:auto; //addition
}
```
