### ISSUE TITLE
Transition issue

### ISSUE THREAD

**Issue by muhamed87** [cssjanus/cssjanus#47]
Hi guys,

I'm facing a small issue in the following rule:
`transform: scaleX(1);`

When running it in the cssjanus there is nothing changed, maybe not all developers need to change this property, but some of them ( I'm one of these developers :) ) for sure need it to be changed to:
`transform: scaleX(-1);`

So I suggest if we can have a comment to be written beside the property and when running into cssjanus it convert it to the desired, something like that one `/* @noflip */`

It can be like:
`transform: scaleX(1); /* @changeto 'transform: scaleX(-1);' */`

**Comment by Krinkle** [comment]
@muhamed87 Thanks for your report.

It sounds like want to use `scaleX()` to horizontally mirror a visual element for RTL mode. That makes perfect sense and is a common technique I've used myself as well. Especially with complicated icons this can save time and removes the need for producing separate icons for example.

However, while this solution is great, it does require the addition of 1 manual rule to make it work.

`scaleX(1)` on its own does not do anything in LTR mode. As such, we cannot reliably use this as an instruction to inverse it in RTL mode.

In this case an RTL-only rule would work best, by using `@noflip`.

For example:

```css
.arrow-start { /* Points left in LTR mode. */
  width: 0; 
  height: 0; 
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent; 
  border-right: 10px solid blue; 
}

/* @noflip */ [dir=rtl] .arrow-start {
  transform: scaleX(-1);
}
```

<img width="725" alt="screen shot 2017-04-20 at 13 59 45" src="https://cloud.githubusercontent.com/assets/156867/25252381/a3d91a10-25d1-11e7-939e-550ad3605170.png">

Note that in this particular example there is actually no need for an override with `@noflip` since CSSJanus would normally already replace border-right with border-left, which naturally makes the triangle point the other way in RTL.
