### ISSUE TITLE
Translate RegExp's are too relaxed which can result in skipping replacements

### ISSUE THREAD

**Issue by TedSander** [cssjanus/cssjanus#69]
It is probably easier to show in code. The following [CSS snippet](https://cssjanus.github.io/#input/drawer%20%7B%0A%20%20transform%3A%20translate(-100%25)%0A%7D%0Adrawer%20%7B%0A%20%20transform%3A%20translate(100%25)%0A%7D) will not flip both transforms:

```css
drawer {
  transform: translate(-100%)
}
drawer {
  transform: translate(100%)
}
```

This seems to be because the transform RegExp is selecting too much. It will work if both or even one of the rules have a [semi-colon](https://cssjanus.github.io/#input/drawer%20%7B%0A%20%20transform%3A%20translate(-100%25)%3B%0A%7D%0Adrawer%20%7B%0A%20%20transform%3A%20translate(100%25)%3B%0A%7D) after it:

```css
drawer {
  transform: translate(-100%);
}
drawer {
  transform: translate(100%);
}
```

I'm not sure if it affects any other rules. This seems more problematic for compilers such as Sass which automatically removes the last semi-colon for properties to save some space.
