### ISSUE TITLE
CSSJanus changes right to left in selectors when using the general sibling combinator

### ISSUE THREAD

**Issue by mainframe98** [cssjanus/cssjanus#85]
When given
```css
#mirage-right-rail-checkbox:checked ~ #mw-navigation #mirage-right-rail-button:before {
  transform: rotate(180deg);
}
``` 
CSSJanus outputs
```css
#mirage-left-rail-checkbox:checked ~ #mw-navigation #mirage-right-rail-button:before {
  transform: rotate(180deg);
}
```
instead of keeping it as is. CSSJanus shouldn't change the id.

It appears this only occurs when the `~` operator is involved. Replacing it with `>` causes the correct behaviour.

Example:
[cssjanus.github.io with the above](https://cssjanus.github.io/#input/%23mirage-right-rail-checkbox%3Achecked%20~%20%23mw-navigation%20%23mirage-right-rail-button%3Abefore%20%7B%0A%20%20transform%3A%20rotate(180deg)%3B%0A%7D)

Related: #5 and #35.
